### ISSUE TITLE
Request for v1.2 package

### ISSUE THREAD

**Issue by am11** [clearlinux-pkgs/libunwind#1]
Announcement: https://savannah.nongnu.org/forum/forum.php?forum_id=8775 (release date: 13 Jan 2017)

v1.1 was released in Oct 2012, a lot of improvements have been made to the core lib since. :)

**Comment by ahkok** [comment]
Testing it atm...

**Comment by ahkok** [comment]
Updated to 1.2. Should be in a release within a day or two.

**Comment by am11** [comment]
Thanks a lot @ahkok! 👍  That was pretty fast 🚀 
Incidentally, would we also have access to v1.1 of the library? I mean how does clearlinux-pkgs support multiple versions of the package from repo's perspective; would we see separate branches for each supported version?

**Comment by ahkok** [comment]
We generally do not want to do this for several reasons, security issues are one. We don't support package branches either (the swupd model can't, and won't, handle it).

**Comment by am11** [comment]
@ahkok, apparently this repo is still building libunwind v1.1. Is there any timeline on the 1.2 update? Thanks!

**Comment by ahkok** [comment]
the repo isn't syncing properly, but clearlinux has 1.2 for a while now:

https://download.clearlinux.org/releases/14640/clear/source/SRPMS/libunwind-1.2-15.src.rpm

**Comment by am11** [comment]
Thanks for the link! 🎉
